# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_product_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
    ]
